// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"LinkMe/internal/api"
	"LinkMe/internal/domain/events/post"
	"LinkMe/internal/repository"
	"LinkMe/internal/repository/cache"
	"LinkMe/internal/repository/dao"
	"LinkMe/internal/service"
	"LinkMe/ioc"
	"LinkMe/utils/jwt"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *Cmd {
	db := ioc.InitDB()
	node := ioc.InitializeSnowflakeNode()
	logger := ioc.InitLogger()
	userDAO := dao.NewUserDAO(db, node, logger)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache, logger)
	userService := service.NewUserService(userRepository, logger)
	handler := jwt.NewJWTHandler(cmdable)
	smsDAO := dao.NewSmsDAO(db, logger)
	smsCache := cache.NewSMSCache(cmdable)
	smsRepository := repository.NewSmsRepository(smsDAO, smsCache)
	tencentSms := ioc.InitSms()
	smsService := service.NewSmsService(smsRepository, logger, tencentSms, smsCache)
	userHandler := api.NewUserHandler(userService, handler, logger, smsService)
	client := ioc.InitMongoDB()
	postDAO := dao.NewPostDAO(db, logger, client)
	postCache := cache.NewPostCache(cmdable, logger)
	postRepository := repository.NewPostRepository(postDAO, logger, postCache)
	interactiveDAO := dao.NewInteractiveDAO(db, logger)
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, logger, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger)
	checkDAO := dao.NewCheckDAO(db, logger)
	checkRepository := repository.NewCheckRepository(checkDAO, logger)
	historyCache := cache.NewHistoryCache(logger, cmdable)
	historyRepository := repository.NewHistoryRepository(logger, historyCache)
	checkService := service.NewCheckService(checkRepository, postRepository, historyRepository, logger)
	saramaClient := ioc.InitSaramaClient()
	syncProducer := ioc.InitSyncProducer(saramaClient)
	producer := post.NewSaramaSyncProducer(syncProducer)
	postService := service.NewPostService(postRepository, logger, interactiveService, checkService, producer, historyRepository, checkRepository)
	postHandler := api.NewPostHandler(postService, logger, interactiveService)
	historyService := service.NewHistoryService(historyRepository, logger)
	historyHandler := api.NewHistoryHandler(historyService, logger)
	enforcer := ioc.InitCasbin(db)
	checkHandler := api.NewCheckHandler(checkService, logger, enforcer)
	v := ioc.InitMiddlewares(handler, logger, enforcer)
	permissionDAO := dao.NewPermissionDAO(enforcer, logger, db)
	permissionRepository := repository.NewPermissionRepository(logger, permissionDAO)
	permissionService := service.NewPermissionService(permissionRepository, logger)
	permissionHandler := api.NewPermissionHandler(permissionService, logger)
	engine := ioc.InitWebServer(userHandler, postHandler, historyHandler, checkHandler, v, permissionHandler)
	interactiveReadEventConsumer := post.NewInteractiveReadEventConsumer(interactiveRepository, saramaClient, logger)
	consumer := ioc.InitConsumers(interactiveReadEventConsumer)
	cmd := &Cmd{
		server:   engine,
		consumer: consumer,
	}
	return cmd
}
