apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: linkme
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: linkme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkme-kafka
  namespace: linkme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "bitnami/kafka:3.6.0"
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9094
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              value: "linkme_binlog:3:1,linkme-sync:3:1,linkme-cache:3:1,linkme-es:3:1"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://192.168.1.11:30880,EXTERNAL://192.168.1.11:9094" # 需将此处改为你的宿主机ip
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@localhost:9093"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_MESSAGE_MAX_BYTES
              value: "20971520"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/bitnami/kafka/data"
          volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami/kafka/data
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: linkme
spec:
  type: NodePort
  ports:
    - name: broker-port
      port: 9092
      nodePort: 30880
    - name: external-port
      port: 9094
      nodePort: 30881
  selector:
    app: kafka