apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkme-kibana
  namespace: linkme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601   # Kibana 默认端口
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: linkme
spec:
  type: NodePort
  ports:
    - port: 5601
      name: http
      nodePort: 30889
  selector:
    app: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: linkme
data:
  kibana.yml: |
    server.name: linkme-kibana
    server.host: "0.0.0.0"   # 监听所有网络接口
    elasticsearch.hosts: [ "http://192.168.1.11:30885" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"