apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkme-record-kafka
  labels:
    app: linkme-record-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkme-record-kafka
  template:
    metadata:
      labels:
        app: linkme-record-kafka
    spec:
      containers:
        - name: linkme-record-kafka
          image: bitnami/kafka:latest
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              # 设置为自己连接kafka使用的ip:端口
              value: "PLAINTEXT://100.64.1.1:30885,EXTERNAL://100.64.1.1:30886"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@localhost:9093"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
          ports:
            - containerPort: 9092
            - containerPort: 9094
          volumeMounts:
            - mountPath: /bitnami/kafka/data
              name: kafka-data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: linkme-kafka-pvc
      restartPolicy: Always
