apiVersion: v1
kind: Service
metadata:
  name: linkme-record-mysql
spec:
  selector:
    app: linkme-record-mysql
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
      nodePort: 30881
  type: NodePort
  