apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkme-logstash
  namespace: linkme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5044   # Beats input port
            - containerPort: 9600   # HTTP monitoring port
          volumeMounts:
            - name: logstash-config-yml
              mountPath: /usr/share/logstash/config/logstash.yml
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
            - name: logstash-storage
              mountPath: /data/logstash
      volumes:
        - name: logstash-config-yml
          hostPath:
            path: /data/logstash/conf/logstash.yml  # 指定配置文件路径
        - name: logstash-config
          hostPath:
            path: /data/logstash/conf/logstash.conf  # 指定配置文件路径
        - name: logstash-storage
          hostPath:
            path: /data/logstash   # 指定数据持久化目录
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: linkme
spec:
  type: NodePort
  ports:
    - port: 5044
      name: beats-input
      nodePort: 30888
    - port: 9600
      name: http-monitoring
      nodePort: 30444
  selector:
    app: logstash