apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkme-redis
  namespace: linkme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
            - "--bind"
            - "0.0.0.0"
            - "--protected-mode"
            - "no"
            - "--port"
            - "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: linkme
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30884
  selector:
    app: redis