version: "3"
services:
  kafka:
    image: "bitnami/kafka:3.6.0"
    container_name: linkme-kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CREATE_TOPICS=linkme_binlog:3:1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.11:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_MESSAGE_MAX_BYTES=20971520
  db:
    image: mysql:8.0
    container_name: linkme-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkme
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    container_name: linkme-redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--bind"
      - "0.0.0.0"
      - "--protected-mode"
      - "no"
      - "--port"
      - "6379"
  mongo:
    image: mongo:latest
    container_name: linkme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes: # 此处是在linux环境下进行 记得给目录添加权限
      - /data/es/data:/usr/share/elasticsearch/data
      - /data/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml # 记得将项目根目录下的elasticsearch.yaml放到/data/es/config/目录下
    ports:
      - "9200:9200"
      - "9300:9300"
  canal:
    image: canal/canal-server
    container_name: linkme-canal
    environment:
      - CANAL_IP=canal-server
      - CANAL_PORT=11111
      - CANAL_DESTINATIONS=linkme
    depends_on:
      - db
      - kafka
    ports:
      - "11111:11111"
    volumes:
      - /data/canal/instance.properties:/home/admin/canal-server/conf/linkme/instance.properties # 配置 Canal 实例的具体参数
      - /data/canal/canal.properties:/home/admin/canal-server/conf/canal.properties # Canal 服务器的全局配置文件
