version: "3"
services:
  kafka:
    image: "bitnami/kafka:3.6.0"
    container_name: linkme-kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CREATE_TOPICS=linkme_binlog:3:1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.11:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_MESSAGE_MAX_BYTES=20971520
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data # 指定 Kafka 数据目录
    volumes:
      - /data/kafka:/bitnami/kafka/data
  db:
    image: mysql:8.0
    container_name: linkme-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkme
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    container_name: linkme-redis
    restart: always
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--bind"
      - "0.0.0.0"
      - "--protected-mode"
      - "no"
      - "--port"
      - "6379"
  mongo:
    image: mongo:latest
    container_name: linkme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=linkme # 设置默认数据库名
    volumes:
      - /data/mongo:/data/db  # 持久化 MongoDB 数据到宿主机的 /data/mongo 目录
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - /data/es/data:/usr/share/elasticsearch/data
      - /data/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml # 记得将项目根目录下的elasticsearch.yaml放到/data/es/config/目录下
    ports:
      - "9200:9200"
      - "9300:9300"
  canal:
    image: canal/canal-server
    container_name: linkme-canal
    environment:
      - CANAL_IP=canal-server
      - CANAL_PORT=11111
      - CANAL_DESTINATIONS=linkme
    depends_on:
      - db
      - kafka
    ports:
      - "11111:11111"
    volumes:
      - /data/canal/sync:/home/admin/canal-server/conf/
      - /data/canal/logs:/home/admin/canal-server/logs
      - /data/canal/destinations:/home/admin/canal-server/destinations
      - /data/canal/canal.properties:/home/admin/canal-server/conf/canal.properties
  prometheus:
    image: bitnami/prometheus:latest
    container_name: linkme-prometheus
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "9090:9090"