package constants

const (
	PostServerERRORCode         = 502001 // 系统错误
	PostEditERRORCode           = 402002 // 帖子编辑错误码
	PostUpdateERRORCode         = 402003 // 帖子更新错误码
	PostPublishERRORCode        = 402004 // 帖子发布错误码
	PostWithdrawERRORCode       = 402005 // 帖子撤销错误码
	PostListPubERRORCode        = 402006 // 公开帖子列表查询错误码
	PostListERRORCode           = 402007 // 个人帖子列表查询错误码
	PostDeleteERRORCode         = 402008 // 帖子删除错误码
	PostGetInteractiveERRORCode = 402009 // 帖子获取互动信息错误码
	PostLikedERRORCode          = 402010 // 帖子点赞错误码
	PostCollectERRORCode        = 402011 // 帖子收藏错误码
	PostGetDetailERRORCode      = 402012 // 帖子获取个人详情错误码
	PostGetPubDetailERRORCode   = 402013 // 帖子获取公开详情错误码
	PostGetLikedERRORCode       = 402014 // 帖子获取点赞信息错误码
	PostGetCollectERRORCode     = 402015 // 帖子获取收藏信息错误码
	PostGetCountERRORCode       = 402016
	PostGetCountSuccess         = "获取帖子数量成功"
	PostGetCountERROR           = "获取帖子数量失败"
	PostEditSuccess             = "帖子编辑成功"              // 帖子编辑成功
	PostUpdateSuccess           = "帖子更新成功"            // 帖子更新成功
	PostPublishSuccess          = "帖子发布成功"           // 帖子发布成功
	PostWithdrawSuccess         = "帖子撤销成功"          // 帖子撤销成功
	PostListPubSuccess          = "公开帖子查询成功"      // 公开帖子查询成功
	PostListSuccess             = "个人帖子查询成功"             // 个人帖子查询成功
	PostDeleteSuccess           = "帖子删除成功"            // 帖子删除成功
	PostGetInteractiveSuccess   = "互动信息获取成功"        // 互动信息获取成功
	PostLikedSuccess            = "帖子点赞成功"             // 帖子点赞成功
	PostCollectSuccess          = "帖子收藏成功"           // 帖子收藏成功
	PostGetDetailSuccess        = "获取帖子详情成功"        // 获取帖子详情成功
	PostGetPubDetailSuccess     = "获取公开帖子详情成功" // 获取公开帖子详情成功
	PostEditERROR               = "帖子编辑失败"                  // 帖子编辑失败
	PostUpdateERROR             = "帖子更新失败"                // 帖子更新失败
	PostPublishERROR            = "帖子发布失败"               // 帖子发布失败
	PostWithdrawERROR           = "帖子撤销失败"              // 帖子撤销失败
	PostListPubERROR            = "公开帖子查询失败"          // 公开帖子查询失败
	PostListERROR               = "个人帖子查询失败"                 // 个人帖子查询失败
	PostDeleteERROR             = "帖子删除失败"                // 帖子删除失败
	PostGetInteractiveERROR     = "互动信息获取失败"            // 互动信息获取失败
	PostLikedERROR              = "帖子点赞失败"                 // 帖子点赞失败
	PostCollectERROR            = "帖子收藏失败"               // 帖子收藏失败
	PostServerERROR             = "系统错误"                 // 系统错误
	PostGetDetailERROR          = "获取帖子详情失败"            // 获取帖子详情失败
	PostGetPubDetailERROR       = "获取公开帖子详情失败"     // 获取公开帖子详情失败
	PostGetLikedERROR           = "获取帖子点赞信息失败"             // 获取帖子点赞信息失败
	PostGetCollectERROR         = "获取帖子收藏信息失败"           // 获取帖子收藏信息失败
	PostGetPostERROR            = "获取帖子失败"              // 获取帖子失败
)
