apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkme-record-mongo
  name: linkme-record-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkme-record-mongo
  template:
    metadata:
      labels:
        app: linkme-record-mongo
    spec:
      containers:
        - image: mongo:latest
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          name: mongo
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "000000"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: linkme-mongo-pvc
