apiVersion: v1
kind: Service
metadata:
  labels:
    app: linkme-record-mongo
  name: linkme-record-mongo
spec:
  ports:
    - name: "27017"
      nodePort: 30884
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: linkme-record-mongo
  type: NodePort
