apiVersion: v1
kind: Service
metadata:
  name: linkme-record-kafka
spec:
  selector:
    app: linkme-record-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30885
      name: "9092"
    - protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30886
      name: "9094"
  type: NodePort
