apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mongo-pv
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"  # 注意此处的挂在点要有读写权限