apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkme-prometheus-pv
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
