apiVersion: v1
kind: Service
metadata:
  name: webook-record-redis
spec:
  selector:
    app: webook-record-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30882
  type: NodePort